### ISSUE TITLE
How are weights duplicated?

### ISSUE THREAD

**Issue by EmmanuelMess** [mszubert/2048#1]
```java
NTuples lines = new NTuplesAllStraightFactory(4, State2048.BOARD_SIZE, 15, 0, 0, new IdentitySymmetryExpander())
		.createRandomIndividual(random);
NTuples squares = new NTuplesAllRectanglesFactory(new RectSize(2, 3), State2048.BOARD_SIZE, 15, 0, 0, new IdentitySymmetryExpander())
		.createRandomIndividual(random);
NTuples vFunction = lines.add(squares);

System.out.println(vFunction.totalWeights());
```

Prints "137092500" that is much more than the amount of weights the paper says "22882500" are used for this configuration. Are some of the weights double counted? How are they shared?

**Comment by wjaskowski** [comment]
Keep in mind that 22882500*6 gives a number very close to 137092500, which might suggest that there should be a symmetric expansion. I am sorry but this code is really very old and I do not remember all the details. You need to track things more closely if you would like to understand whether there is some kind of sharing or we make an error in reporting. 

Also, note that there is an extended version of the ideas from this work in https://github.com/wjaskowski/mastering-2048.
